### ISSUE TITLE
Example does not run

### ISSUE THREAD

**Issue by RpfR2000** [JuliaImages/IntegralArrays.jl#19]
I can't get the example to run when defining the plus/minus operator in the usual way (i.e., `±(a::Number, b::Number) = a + b, a - b`). When I modify the example to something that does work, m1 does not equal m2. Here was my modification. Maybe I am misunderstanding the way the mean was supposed to be calculated from the integral image. 

```
function mean_filter_integral!(out, X)
    iX = IntegralArray(X)
    for i in CartesianIndex(2, 2):CartesianIndex(size(X).-1)
        x, y = i.I
        block = iX[x+1, y+1] - iX[x-1, y+1] - iX[x+1, y-1] + iX[x-1, y-1]
        out[i] = block / 4 
    end
    return out
end
```

**Comment by timholy** [comment]
Try `using IntervalSets`

**Comment by timholy** [comment]
Also, there are 9 blocks, not 4, in the range: `x-1:x+1` has 3 elements

**Comment by RpfR2000** [comment]
Awesome thanks!
